title: Ragol.co.uk
description: A Phantasy Star Online Fansite
url: https://ragol.co.uk

collections:
  news:
    output: false
  guides:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: guides
    values:
      layout: guide

permalink: pretty

plugins:
  - jekyll-sitemap
