title: Ragol.co.uk
description: A Phantasy Star Online Fansite
url: https://ragol.co.uk

collections:
  articles:
    output: true
  guides:
      output: true
  news:
    output: false

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: articles
    values:
      layout: article
  - scope:
      path: ""
      type: guides
    values:
      layout: article

permalink: pretty

plugins:
  - jekyll-sitemap
